### ISSUE TITLE
using id 1 for race throws error

### ISSUE THREAD

**Issue by Nercus** [Miorey/wow-model-viewer#10]
If the id for human is chosen as race the following error gets thrown:
```
index.js:274 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Id')
    at getOptions (index.js:274:92)
    at optionsFromModel (index.js:194:27)
    at async generateModels (index.js:215:26)
```

**Comment by Miorey** [comment]
@Nercus can you link your code please ?

**Comment by Nercus** [comment]
sorry forgot that. Here is a simple codesandbox to switch between race values 1 (human) and 2 (orc). I actually discovered that other properties also throw the same error when value is set to 1.

https://codesandbox.io/s/cranky-bose-knj9jk?file=/src/App.vue

**Comment by Miorey** [comment]
@Nercus [TrinityCore](https://github.com/TrinityCore/TrinityCore) / [AzerothCore](https://github.com/azerothcore) are two WoW emulators based on mangos (one of the first wow emulator). I create this library for my wow server armory, and I get the characters style from db with the values set by the official. So I never faced your issue or at the begging when I investigate how wowhead works.
